package:
  name: "mirp"
  version: "1.0.1"

source:
  path: ../

requirements:
  build:
    - python {{ python }}
    - setuptools
    - pip

  run:
    - python
    - numpy >=1.17.0
    - scipy >=1.3.0
    - pandas >=0.25.0
    - pydicom >=1.3.0
    - pywavelets >=1.0.0
    - scikit-image >=0.15.0
    - SimpleITK >=1.2.0

about:
  home: https://github.com/oncoray/mirp
  license: EUPL1.2
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Medical Image Radiomics Processor
  doc_url: https://github.com/oncoray/mirp
